services:
  app:
    build: .
    container_name: dev-burguer-app
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}   # verifique nome consistente
      - MONGO_URL=${MONGO_URL}
      - PORT=3001
    depends_on:
      - db_postgres
      - db_mongo
    restart: unless-stopped

  db_postgres:
    image: postgres:15
    container_name: dev-burguer-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_mongo:
    image: mongo:6
    container_name: dev-burguer-mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:




